spring.application.name=rollerspeed

# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5433/rollerspeed 
spring.datasource.username=postgres
spring.datasource.password=1031
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect




